# Generated by Django 6.0.5 on 2026-05-23 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("dosage", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "type_medicament",
                    models.CharField(
                        choices=[
                            ("comprime", "Comprimé"),
                            ("effervescent", "Effervescent"),
                            ("sirop", "Sirop"),
                            ("suppositoire", "Suppositoire"),
                            ("capsule", "Capsule"),
                            ("injection", "Injection"),
                            ("autre", "Autre"),
                        ],
                        default="comprime",
                        max_length=20,
                    ),
                ),
                ("contre_indications", models.TextField(blank=True, null=True)),
                ("effets_secondaires", models.TextField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("notice_json", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Boitier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(default="Mon Boîtier", max_length=100)),
                ("adresse_mac", models.CharField(blank=True, max_length=50, null=True)),
                ("batterie", models.IntegerField(default=100)),
                ("est_connecte", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boitier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Traitement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "port",
                    models.CharField(
                        choices=[("A", "Port A"), ("B", "Port B")], max_length=1
                    ),
                ),
                ("horaires", models.JSONField(default=list)),
                ("duree_totale", models.IntegerField(help_text="Durée en jours")),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("jours_restants", models.IntegerField()),
                ("est_actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "boitier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traitements",
                        to="api.boitier",
                    ),
                ),
                (
                    "medicament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.medicament"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horaire_prevue", models.TimeField()),
                ("horaire_reelle", models.TimeField(blank=True, null=True)),
                ("date_prise", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("prise", "Prise"),
                            ("retard", "Retard"),
                            ("oublie", "Oubliée"),
                        ],
                        default="prise",
                        max_length=10,
                    ),
                ),
                (
                    "traitement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prises",
                        to="api.traitement",
                    ),
                ),
            ],
            options={
                "unique_together": {("traitement", "date_prise", "horaire_prevue")},
            },
        ),
    ]
