# Generated by Django 4.2.30 on 2026-05-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='code_cis',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='forme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicament',
            name='statut',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
