# Generated by Django 4.2.30 on 2026-05-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicament_code_cis_medicament_forme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(choices=[('A', 'Port A'), ('B', 'Port B')], max_length=1)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boitier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_configs', to='api.boitier')),
            ],
            options={
                'unique_together': {('boitier', 'port')},
            },
        ),
    ]
